### ISSUE TITLE
InvalidArgumentError: indices[36864] = [1, 24, 0, 0] does not index into shape [8,24,24,256]

### ISSUE THREAD

**Issue by GilbertoManunta** [tnybny/Frame-level-anomalies-in-videos#13]
Hi, i have this issue while launching the main.py:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[36864] = [1, 24, 0, 0] does not index into shape [8,24,24,256]
	 [[{{node ScatterNd}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/Desktop/Gilby/UNI/TESI/Frame-level-anomalies-in-videos-master/main.py", line 50, in <module>
    frame_gt_path=FRAME_GT_PATH, result_path=result_path, model_path=model_path)
  File "C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\train.py", line 21, in train
    loss = model.batch_train()
  File "C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\conv_AE_2D.py", line 166, in batch_train
    self.handle: self.training_handle})
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[36864] = [1, 24, 0, 0] does not index into shape [8,24,24,256]
	 [[node ScatterNd (defined at C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\max_unpool.py:36) ]]

Caused by op 'ScatterNd', defined at:
  File "C:/Users/User/Desktop/Gilby/UNI/TESI/Frame-level-anomalies-in-videos-master/main.py", line 42, in <module>
    net = ConvAE2d(data=d, alpha=ALPHA, lambd=LAMBDA)
  File "C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\conv_AE_2D.py", line 43, in __init__
    self.y = self.spatial_decoder(self.conved, shapes, masks)
  File "C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\conv_AE_2D.py", line 144, in spatial_decoder
    unpool1 = unpool(deconv1, mask=mask)
  File "C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\max_unpool.py", line 36, in unpool
    ret = tf.scatter_nd(indices, values, output_shape)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7824, in scatter_nd
    "ScatterNd", indices=indices, updates=updates, shape=shape, name=name)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[36864] = [1, 24, 0, 0] does not index into shape [8,24,24,256]
	 [[node ScatterNd (defined at C:\Users\User\Desktop\Gilby\UNI\TESI\Frame-level-anomalies-in-videos-master\src\max_unpool.py:36) ]]

Any solution?

Thank you

**Comment by tnybny** [comment]
I think this has something to do with getting your environment right -- could you give me some details about that? For example, I see you are on Python 3.7, but this code has only been tested on Python 2.7. Additionally, the max_unpool layer requires that you be running this on a cuda compatible GPU.

**Comment by tnybny** [comment]
I would also try tensorflow-gpu version <=1.12

**Comment by GilbertoManunta** [comment]
I'm using tensorflow cpu version because my laptop gpu does not have enough computational power

**Comment by tnybny** [comment]
That explains it. Unfortunately the max_unpool layer implementation has GPU-specific operations (ScatterNd if I remember right). If you're fine with replacing the max_pool_with_argmax and unpool layers with other similar layers in the Tensorflow libraries, you should be able to run it.

Additionally, you might want to try the STAE method by setting that in config/config.ini which does not use these layers.

**Comment by GilbertoManunta** [comment]
Thank you for your help and quick response. I will think about your suggestions.

Have a nice day.

**Comment by tnybny** [comment]
Anytime, good luck!
